Prevent multiple editors on a submission
microbiomedata/nmdc-server pull request #1098
Opened 2023-12-08 18:52 UTC by naglepuff

Fix #1076 

This group of changes disables multiple people accessing a single submission at the same time. This prevents users getting their changes overridden by others on the rare occasion that they are editing the same submission simultaneously. It contains front end and back end changes.

## Backend

1. Data model changes: the `SubmissionMetadata` model now contains a second foreign key to the user table representing the user who currently holds the "lock" for that submission, and a timestamp representing when the last edit was made. A submission "lock" refers to the combination of these new fields.
2. An accompanying migration file is included.
3. New functions were added in `crud.py` for attempting to obtain the lock, updating the lock, and releasing the lock.
4. Existing `/api/metadata_submission` routes were updated to include lock checking
5. A new endpoint was added to release the lock for a submission.

## Frontend

@mslarae13 a full read-only mode will likely be available once #1077 is developed, which will likely replace this approach. I'm happy to discuss further at squad meetings.

1. If a user attempts to access a locked submission from the submission list, they will be shown a message that informs them that the submission is currently locked, and offer to take them back to the submission list. The name (if available, ORCID iD if not) is shown to the user.
2. If a user editing a submission navigates away from any screen that lets them edit the submission (for example, going back to the submission list, navigating away from the NMDC Submission Portal entirely, or closing the tab/window), the submission becomes unlocked.

 
![image](https://github.com/microbiomedata/nmdc-server/assets/7085625/372deb52-a0f8-4a67-a804-ec20b703161b)

Note for testing before this gets deployed: I believe ORCID doesn't like people having multiple accounts. To test this locally I used the ORCID sandbox environment [sandbox.orcid.org ](https://sandbox.orcid.org/)to create multiple users (using variations on mike.nagler+xyz@kitware.com). Reach out for more help setting this up.

2023-12-09 00:23 UTC, mslarae13 commented
looks great Mike! Maybe we can demo the next time we meet for UFO.

2024-01-08 15:46 UTC, marySalvi requested changes

2024-01-08 15:46 UTC, marySalvi commented on web/src/views/SubmissionPortal/StepperView.vue
> +    <!-- Put locked by notification/banner here -->
Is this comment still needed?

2024-01-08 16:03 UTC, naglepuff commented on web/src/views/SubmissionPortal/StepperView.vue
> +    <!-- Put locked by notification/banner here -->
Whoops. removed in f384bfc

2024-01-08 16:05 UTC, naglepuff commented on nmdc_server/crud.py
> +                submission_record.lock_updated = datetime.utcnow()
Good catch. I un-indented that last else clause. Which is kind of a paranoid guard against submissions that are locked with no timestamp. addb7fb

2024-01-08 16:07 UTC, naglepuff commented on nmdc_server/api.py
> +    _ = crud.try_get_submission_lock(db, submission.id, user.id)
I removed the assignment and reordered the checks in 2298bc5

The behavior of this endpoint is the same regardless of whether or not the user requesting has the submission locked, which is why we don't need to use the returned value.

2024-01-08 16:36 UTC, marySalvi approved these changes

2024-01-09 19:29 UTC, merged