Study page refresh
microbiomedata/nmdc-server pull request #1120
Opened 2024-01-25 16:42 UTC by marySalvi

2024-01-31 19:37 UTC, naglepuff requested changes
A couple style things and one question about the study API change. This was just a first pass at code review. I still have to run an ingest and do functional testing.

It might be a good idea to see how long it would take to add a couple of tests for the study API. I imagine that would involve updating the Study model factory.

2024-02-05 20:10 UTC, naglepuff requested changes
I'm currently poking around at this locally. I've noticed a few things so far. A couple of search issues and some stuff that I think is just front-end.

Let me know if you want to investigate any of these together.

2024-02-05 20:10 UTC, naglepuff commented on nmdc_server/api.py
If I add the filter `local environmental context === wetland ecosystem`, I get the correct number of samples and omics counts  (by correct I mean this branch matches what is in dev).

The study count is also correct (2), but only 1 study is shown. The missing study is `gold:Gs0110138`, which is a child study of `nmdc:sty-11-cytnjc39`, in case that helps find the issue.

2024-02-06 21:33 UTC, marySalvi commented on nmdc_server/api.py
> +                    parent.children.append(child)
Hmm good question. I can see an argument for both. @lamccue @mslarae13 What do you think should happen in this instance?

2024-02-08 18:12 UTC, mslarae13 commented on nmdc_server/api.py
> +                    parent.children.append(child)
I think yes. 

So this is ONLY for running a query.

If the child study matches, and the parent study matches. Show both. If only the child matches, only show the child.

So, I'm searching by PI specifically. The PI for my child is different that the parent. Show only the child

But like Mary I can see a good reason to always show parents if at least 1 of its children are present

I want to know @lamccue 's thoughts and am curious on @aclum 's thoughts at the data portal product owner.

2024-02-08 20:53 UTC, mslarae13 commented
from 2024-02-08

make DOI provider capitalized emsl to EMSL jgi to JGI
Remove associated studies when not populated
Get associated studies on parent page
Add study title with study ID 

@marySalvi

2024-02-14 17:19 UTC, marySalvi commented on nmdc_server/api.py
> +        # study_results["results"] = top_level_studies
removed in ed4ee4d920f465062059c6893767108eac285a59

2024-02-14 17:19 UTC, marySalvi commented on nmdc_server/api.py
> +                    parent.children.append(child)
fixed in ed4ee4d920f465062059c6893767108eac285a59

2024-02-14 17:19 UTC, marySalvi commented on web/src/data/api.ts
> +  value: string | number | [number, number] ;
removed in ed4ee4d920f465062059c6893767108eac285a59

2024-02-14 17:20 UTC, marySalvi commented on web/src/views/IndividualResults/StudyPage.vue
> +    };
removed in ed4ee4d920f465062059c6893767108eac285a59

2024-02-14 17:20 UTC, marySalvi commented on web/src/views/Search/SearchLayout.vue
> +                @set-items-per-page="study.setItemsPerPage($event)"
fixed in ed4ee4d920f465062059c6893767108eac285a59

2024-02-14 17:20 UTC, marySalvi commented on web/src/views/Search/SearchLayout.vue
> +                            >
fixed in ed4ee4d920f465062059c6893767108eac285a59

2024-02-14 17:20 UTC, marySalvi commented on web/src/views/Search/SearchLayout.vue
> +                disable-navigate-on-click
fixed in ed4ee4d920f465062059c6893767108eac285a59

2024-02-14 17:21 UTC, marySalvi commented on nmdc_server/api.py
fixed in ed4ee4d920f465062059c6893767108eac285a59

2024-02-14 17:21 UTC, marySalvi commented on nmdc_server/api.py
fixed in ed4ee4d920f465062059c6893767108eac285a59

2024-02-14 19:15 UTC, naglepuff commented on web/src/views/Search/SearchLayout.vue
> +                @set-items-per-page="study.setItemsPerPage($event)"
Looks like this was fixed

2024-02-15 01:16 UTC, marySalvi commented on web/src/views/Search/SearchLayout.vue
> +                      @change="setChecked(result.id, result.children)"
fixed in 31b8788b487824cf94affbd3f14ea9dd29f47d27

2024-02-15 20:34 UTC, naglepuff commented on web/src/views/Search/SearchLayout.vue
> +                      @change="setChecked(result.id, result.children)"
Tested these changes locally, checkbox behavior looks good to me!

2024-02-15 20:36 UTC, naglepuff approved these changes
Apart from the GH action test failures, LGTM! Once those are fixed let's ship it to dev and get other people testing it!

2024-02-15 21:48 UTC, merged