1303 add gold tooltip
microbiomedata/nmdc-server pull request #1346
Opened 2024-08-15 16:30 UTC by marySalvi

closes #1303 
- Adds tooltip for GOLD Ecosystems
- Also converts all schema JSON references to yaml

2024-08-20 21:28 UTC, naglepuff requested changes

2024-08-20 21:28 UTC, naglepuff commented on web/src/components/MenuContent.vue
I don't see facet definitions anymore. Is this expected? Do these need to be populated in the schema again?

Prod:
![image](https://github.com/user-attachments/assets/c50acc89-a78a-465a-9006-190e42339d74)

This branch:
![image](https://github.com/user-attachments/assets/ca785438-abc7-4252-9d2f-c8b43c863a02)

2024-08-21 14:07 UTC, marySalvi commented on web/src/components/MenuContent.vue
Good catch, I'll look into this

2024-08-21 19:52 UTC, aclum commented
@marySalvi  how are things coming along with the change requests? Will we be able to include this feature in the monthly release scheduled for Monday?

2024-08-21 21:30 UTC, marySalvi commented
> @marySalvi how are things coming along with the change requests? Will we be able to include this feature in the monthly release scheduled for Monday?

@aclum Yes, this should be able to be included.

2024-08-22 17:59 UTC, marySalvi commented on web/src/components/MenuContent.vue
fixed in 27d656faf1c44922354cf864f984d20f4b5febd2

2024-08-22 18:00 UTC, marySalvi commented on web/src/data/api.ts
> +import nmdc from 'nmdc-schema/nmdc_schema/nmdc_materialized_patterns.yaml';
changed in 1009546afe4126182a42f76c1866e5c267fdf0fa

2024-08-22 18:47 UTC, naglepuff approved these changes
Great! I see the text in the sidebar flyouts again.

2024-08-22 18:54 UTC, merged