Ingest COG terms, pathways and functions
microbiomedata/nmdc-server pull request #1359
Opened 2024-08-22 18:36 UTC by naglepuff

Fix #1333

2024-09-05 22:27 UTC, ssarrafan commented
@marySalvi can this be reviewed by tomorrow so we can close the issue this sprint?

2024-09-06 13:25 UTC, marySalvi commented
> @marySalvi can this be reviewed by tomorrow so we can close the issue this sprint?

Yes, I'll have this reviewed today

2024-09-06 19:54 UTC, marySalvi requested changes
Looks good with some minor changes. I also had to run inside container. I don't know if that it a blocker

2024-09-06 19:54 UTC, marySalvi commented on nmdc_server/ingest/kegg.py
>      datafile = Path(__file__).parent / "data" / "kegg_module_ko_terms.tab.txt"
```suggestion
    datafile = Path(__file__).parent / "data" / "kegg" / "kegg_module_ko_terms.tab.txt"
```

2024-09-06 19:54 UTC, marySalvi commented on nmdc_server/ingest/kegg.py
>      datafile = Path(__file__).parent / "data" / "ko_term_pathways.tab.txt"
```suggestion
    datafile = Path(__file__).parent / "data" / "kegg" / "ko_term_pathways.tab.txt"
```

2024-09-06 20:16 UTC, marySalvi requested changes

2024-09-06 20:16 UTC, marySalvi commented on nmdc_server/ingest/kegg.py
> +    with open(COG_TERM_DEFS) as fd:
```suggestion
    cogterms = Path(__file__).parent / "data" / "cog" / "cog-20.def.tab"
    with open(cogterms) as fd:
```

this is the docker culprit

2024-09-06 20:16 UTC, marySalvi commented on nmdc_server/ingest/kegg.py
> +    with open(COG_TERM_DEFS) as fd:
```suggestion
    cogterms = Path(__file__).parent / "data" / "cog" / "cog-20.def.tab"
    with open(cogterms) as fd:
```
ditto from above

2024-09-06 20:42 UTC, naglepuff commented
@ssarrafan we're going to hold off on merging this until next week. There are some aspects of this part of ingest that we'd like to discuss a little bit more internally. I expect that to be resolved early next week though (Monday or Tuesday)

2024-09-11 16:13 UTC, marySalvi approved these changes

2024-09-12 17:57 UTC, merged