Add user models
microbiomedata/nmdc-server pull request #702
Opened 2022-06-08 13:19 UTC by DeepikaGhodki

https://github.com/microbiomedata/nmdc-server/issues/689

TODO- replace references of ORCID

2022-06-10 14:25 UTC, subdavis requested changes
Code looks great!  I have a few mostly minor comments.  Once these changes have been addressed, I will download and run this PR.

2022-06-10 14:25 UTC, subdavis commented on nmdc_server/schemas.py
> +    user: Optional[User]
Change to `author`.

2022-06-10 15:54 UTC, turbomam commented
This is great. We will need to synchronize any modeling here with the nmdc-schema

2022-06-10 16:52 UTC, DeepikaGhodki commented on nmdc_server/auth.py
> +        )
Ideally, we should never run into this as every user who is able to reach here would have logged in and hence user should be always found. And now that we are handling the user addition in migration, we will never encounter a scenario where there's a submission for user not present in the system. 

My thought process here was that irrespective of how the user got here, if we can't validate we consider it as an invalid case. If this happens with a valid user, then they may login again. I see your point through, 403 could confuse the user. 
If we are propagating the error message, we can add an actionable message. 

Or we could let it fail with an unexpected error i.e. without raising any exception. But what would the user do then? Reload the page, and retry maybe?

2022-06-15 15:49 UTC, turbomam commented
Is there any documentation for this, or a non-code serialization of the model?

2022-06-15 16:06 UTC, merged