Allow multiple biosamples per omics processing
microbiomedata/nmdc-server pull request #991
Opened 2023-07-12 21:36 UTC by naglepuff

2023-07-14 13:12 UTC, jeffbaumes requested changes
I ran an ingest off this branch with the following resulting table:

```
jeff.baumes@mediumblue nmdc-server % docker-compose run backend psql -c "select omics_processing_id, count(*) from biosample_input_association group by omics_processing_id order by count DESC limit 10;" -d nmdc_a
[+] Running 2/0
 ⠿ Container nmdc-server-redis-1  Running                                                                                                                                                                   0.0s
 ⠿ Container nmdc-server-db-1     Running                                                                                                                                                                   0.0s
  omics_processing_id   | count 
------------------------+-------
 nmdc:omprc-11-s9xj2r24 |     3
 nmdc:omprc-11-0cwmmn51 |     1
 emsl:598512            |     1
 emsl:739468            |     1
 nmdc:omprc-11-348wr426 |     1
 emsl:457882            |     1
 emsl:458282            |     1
 nmdc:omprc-11-dk2cv159 |     1
 nmdc:omprc-11-f2wyjt42 |     1
 emsl:747985            |     1
(10 rows)
jeff.baumes@mediumblue nmdc-server % docker-compose run backend psql -c "select * from biosample_input_association where omics_processing_id = 'nmdc:omprc-11-s9xj2r24'" -d nmdc_a 
[+] Running 2/0
 ⠿ Container nmdc-server-db-1     Running                                                                                                                                                                   0.0s
 ⠿ Container nmdc-server-redis-1  Running                                                                                                                                                                   0.0s
  omics_processing_id   |    biosample_id     
------------------------+---------------------
 nmdc:omprc-11-s9xj2r24 | nmdc:bsm-99-abcdef1
 nmdc:omprc-11-s9xj2r24 | nmdc:bsm-99-abcdef2
 nmdc:omprc-11-s9xj2r24 | nmdc:bsm-99-abcdef3
(3 rows)
```

The number of omics_processings for the NEON study seem to be 2 less than the number of samples. I believe this is expected because one omics_processing has 3 samples as input since they were pooled instead of the normal 1:1.

<img width="1151" alt="image" src="https://github.com/microbiomedata/nmdc-server/assets/81305/d32868d2-8b25-4519-bcc8-024f39da2c36">

If I search by "Local Environmental Context" as "coal mine" I only get the mock samples, and they all have an omics_processing

<img width="1153" alt="image" src="https://github.com/microbiomedata/nmdc-server/assets/81305/42aee3db-053b-455e-bb01-e90fa6d098bd">

So this all seems to be working as expected so far. I requested a couple of dead code removal changes.

2023-07-14 20:22 UTC, naglepuff commented on nmdc_server/filters.py
> +            # ),
4661eec

2023-07-14 20:22 UTC, naglepuff commented on nmdc_server/filters.py
> +            # ),
4661eec

2023-07-18 20:03 UTC, jeffbaumes approved these changes

2023-07-18 20:32 UTC, merged